CREATE TABLE IF NOT EXISTS Request_Type (
    request_type_id INT AUTO_INCREMENT PRIMARY KEY,
    outlet_type VARCHAR(255),
    request_type VARCHAR(255)
);

INSERT INTO Request_Type (
    outlet_type,
    request_type
) VALUES 
("New", "Beer Garden"),
("New", "Full/New Development"),
("New", "COE"),
("New", "Drinking Location Development"),
("New", "Sathosa - Basic Development"),
("New", "Non Branding Elements"),
("Existing", "Beer Garden"),
("Existing", "Full/New Development"),
("Existing", "COE"),
("Existing", "Drinking Location Development"),
("Existing", "Sathosa - Basic Development"),
("Existing", "Non Branding Elements"),
("Existing", "Regular Maintenance");

CREATE TABLE IF NOT EXISTS Branding_Elements_Type (
    branding_elements_type_id INT AUTO_INCREMENT PRIMARY KEY,
    branding_elements_type VARCHAR(255)
);

INSERT INTO Branding_Elements_Type (
    branding_elements_type
) VALUES 
("3*4 Board"),
("DJ Booth"),
("Outdoor Counter"),
("Counter Panel"),
("Wall branding"),
("Garden Lights"),
("LED Light boards – with human elements"),
("LED Light Board – Other"),
("Table branding – Embossing"),
("Wooden Tables"),
("Wooden Benches"),
("Bean Bags"),
("Bar stools"),
("Verandah Chairs – Wooden"),
("Chairs - Other"),
("Garden Umbrella"),
("DJ Booth Branding"),
("Ceiling related work"),
("Colour Washing"),
("Iron Benches"),
("Portable Draught"),
("Counter"),
("Display Shelves"),
("Shelf Headers"),
("Cooler Branding"),
("LED Boards (Human Elements light board)"),
("LED Boards – other"),
("LED Bottle unit"),
("Standing Lion Unit"),
("Pillar Branding"),
("Chairs – Other"),
("Garden Umbrellas"),
("Retail facia design (Customized Spec)"),
("Retail facia design Cladding"),
("3*4 board – (Customized Spec)"),
("Allocation of a “Hot-Spot” within the premises-"),
("LED Bottle unit- LION"),
("LED Bottle unit- other"),
("Multibranded unit from Luxury Brands"),
("Lighted Embossed letters"),
("Counter Panel (Customized Spec)"),
("Shelf header"),
("AC Units"),
("Tempered Glass Doors"),
("Shelves and Racks"),
("Ceiling designing"),
("Partitioning"),
("Floor Tiling"),
("Ceiling Fans / Lights"),
("Benches-Wooden"),
("Plastic stools"),
("Chairs – Plastic"),
("Wall mounted - Shot tables Wooden"),
("Rotating fans"),
("Glass shelf for bites"),
("Wall branding images"),
("Price board (Where applicable)"),
("Racks"),
("Wall Painting"),
("Outlet wiring"),
("3” GI Pipe"),
("Roller blinds"),
("Ceiling"),
("Ceiling lights"),
("Main door"),
("Stores door");

CREATE TABLE IF NOT EXISTS Request_Branding_Elements_Type (
    req_branding_elements_type_id INT AUTO_INCREMENT PRIMARY KEY,
    request_type_id INT,
    request_type VARCHAR(255),
    branding_elements_type_id INT,
    branding_elements_type VARCHAR(255),
    is_active BOOLEAN, 
    created_by VARCHAR(255), 
    created_on DATETIME, 
    updated_by VARCHAR(255), 
    updated_on DATETIME,
    FOREIGN KEY (request_type_id) REFERENCES Request_Type(request_type_id),
    FOREIGN KEY (branding_elements_type_id) REFERENCES Branding_Elements_Type(branding_elements_type_id),
    UNIQUE (request_type_id, branding_elements_type_id)
);