CREATE TABLE IF NOT EXISTS Request (
    request_id INT NOT NULL AUTO_INCREMENT,
    is_new_outlet BOOLEAN,
    request_type_id INT,
    outlet_info_id INT,
    rt_code VARCHAR(8),
    territory_info_id INT,
    channel_info_id INT,
    outlet_name VARCHAR(40),
    address_line1 VARCHAR(40),
    address_line2 VARCHAR(40),
    address_line3 VARCHAR(40),
    address_line4 VARCHAR(40),
    address_line5 VARCHAR(40),
    drive_brand_id INT,
    is_chain_outlet BOOLEAN,
    chain_name VARCHAR(40),
    is_urgent BOOLEAN,
    status_id INT,
    stage_id INT,
    contact_name VARCHAR(40),
    contact_email VARCHAR(40),
    contact_address VARCHAR(40),
    contact_number INT,
    bq_outlet_volume INT,
    bq_competitor_threat_id INT,
    bq_is_strategic_location BOOLEAN,
    bq_consumer_profile VARCHAR(40),
    bq_last_cost_incurred FLOAT,
    bq_portfolio_share FLOAT,
    bq_is_design_with_boq BOOLEAN,
    bq_sales_volume INT,
    tm_email VARCHAR(40),
    fsm_email VARCHAR(40),
    cdm_email VARCHAR(40),
    designer_email VARCHAR(40),
    supplier_email VARCHAR(40),
    auditor_email VARCHAR(40),
    bm_email VARCHAR(40),
    pr_number_designer INT,
    pr_date_designer DATETIME,
    po_number_designer INT,
    po_date_designer DATETIME,
    quotation_value_designer FLOAT,
    pr_number_supplier INT,
    pr_date_supplier DATETIME,
    po_number_supplier INT,
    po_date_supplier DATETIME,
    quotation_value_supplier FLOAT,
    artwork_approved_on DATETIME,
    measurement_completed_on DATETIME,
    quotation_received_on DATETIME,
    work_completed_on DATETIME,
    tm_signed_off_on DATETIME,
    cdm_signed_off_on DATETIME,
    hod_approved_on DATETIME,
    PRIMARY KEY (request_id),
    FOREIGN KEY (request_type_id) REFERENCES Request_Type(request_type_id),
    FOREIGN KEY (outlet_info_id) REFERENCES Outlet_Info(outlet_info_id),
    FOREIGN KEY (territory_info_id) REFERENCES Territory_Info(territory_info_id),
    FOREIGN KEY (channel_info_id) REFERENCES Channel_Info(channel_info_id),
    FOREIGN KEY (drive_brand_id) REFERENCES Brand_Info(brand_info_id),
    FOREIGN KEY (status_id) REFERENCES Lookup(lookup_id),
    FOREIGN KEY (stage_id) REFERENCES Lookup(lookup_id),
    FOREIGN KEY (tm_email) REFERENCES user(email),
    FOREIGN KEY (cdm_email) REFERENCES user(email),
    FOREIGN KEY (designer_email) REFERENCES user(email),
    FOREIGN KEY (supplier_email) REFERENCES user(email),
    FOREIGN KEY (auditor_email) REFERENCES user(email)
);